# See config.example.yml for documentation.
object_base: orig/RKXE69
object: sys/main.dol
hash: 8adc15c745cbc665a35929ce5b2530673ff6b817
symbols: config/RKXE69/symbols.txt
splits: config/RKXE69/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14
